# Generated by Django 5.1 on 2024-08-30 13:32

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('en_title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی انگلیسی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان مقاله را وارد کنید', max_length=200, verbose_name='عنوان مقاله')),
                ('en_title', models.CharField(help_text='عنوان مقاله را وارد کنید انگلیسی', max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(help_text='آدرس مقاله را میتوانید از اینجا عوض کنید،(نکته: فقط در زمان ویرایش مقاله امکان تغییر آدرس وجود دارد) اما با عوض کردن آن آدرس قبلی در دسترس نخواهد بود', max_length=100, verbose_name='آدرس مقاله')),
                ('description', ckeditor.fields.RichTextField(help_text='محتوای مقاله را وارد کنید', verbose_name='مقاله')),
                ('en_description', ckeditor.fields.RichTextField(help_text='محتوای مقاله را وارد کنید انگلیسی', verbose_name='مقاله')),
                ('thumbnail', models.ImageField(help_text='تصویری که میخواهید به عنوان کاور مقاله قرار بگیرد را وارد کنید', upload_to='images/blog/%Y/%m/%d', verbose_name='تصویر مقاله')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('category', models.ForeignKey(help_text='دسته بندی پست خود را وارد کنید', on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='articles.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-pub_date'],
            },
        ),
    ]
