# Generated by Django 5.0 on 2024-08-31 13:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='en_description',
            field=ckeditor.fields.RichTextField(help_text='محتوای مقاله را وارد کنید انگلیسی', verbose_name='مقاله انگلیسی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='en_title',
            field=models.CharField(help_text='عنوان مقاله را وارد کنید انگلیسی', max_length=200, verbose_name='عنوان مقاله انگلیسی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='آدرس مقاله را میتوانید از اینجا عوض کنید،(نکته: فقط در زمان ویرایش مقاله امکان تغییر آدرس وجود دارد) اما با عوض کردن آن آدرس قبلی در دسترس نخواهد بود', max_length=100, unique=True, verbose_name='آدرس مقاله'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی'),
        ),
    ]
