# Generated by Django 5.0 on 2024-09-02 10:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(help_text='محتوای مقاله را وارد کنید', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='en_description',
            field=tinymce.models.HTMLField(help_text='محتوای مقاله را وارد کنید انگلیسی', verbose_name='مقاله انگلیسی'),
        ),
    ]
