# Generated by Django 5.0 on 2024-09-02 10:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیحات دسته بندی اختیاری'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیحات دسته بندی انگلیسی اختیاری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات و اطلاعات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='en_description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات و اطلاعات انگلیسی'),
        ),
    ]
