# Generated by Django 5.0 on 2024-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='more_product',
            field=models.ManyToManyField(blank=True, to='products.product', verbose_name='محصولات مرتبط'),
        ),
    ]
